AllCops:
  Exclude:
    - 'test/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'gotchable.gemspec'
  TargetRubyVersion: 2.3
  AutoCorrect: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/UnneededPercentQ:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/NumericPredicate:
  Enabled: true

Naming/PredicateName:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 1200

Metrics/ClassLength:
  Max: 1200

Metrics/MethodLength:
  Max: 1200

Metrics/ModuleLength:
  Max: 1200

Metrics/BlockLength:
  Max: 1200

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Rails/FindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/LambdaCall:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: true

Layout/AlignHash:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Layout/AlignArray:
  Enabled: true

Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Enabled: true
